export const USER_LOADING = 'USER_LOADING';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_AUTH_USER = 'GET_AUTH_USER';
export const AUTH_ERRORS = 'AUTH_ERRORS';

//dOCTOR
/*
  export const DOCTOR_LOADING = 'DOCTOR_LOADING';
  export const LOGIN_DOCTOR = 'LOGIN_DOCTOR';
  export const REGISTER_DOCTOR = 'REGISTER_DOCTOR';
  export const LOGOUT_DOCTOR = 'LOGOUT_DOCTOR';
  export const GET_AUTH_DOCTOR = 'GET_AUTH_DOCTOR';

*/



//Profile action
export const CREATE_PROFILE='CREATE_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const EDIT_PROFILES = 'EDIT_PROFILES';
//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//Medical file 

export const  GET_MEDICALFILES="GET_MEDICALFILES";
export const POST_MEDICALFILES="POST_MEDICALFILES";
//export const AUTH_ERRORS="AUTH_ERRORS";
//export const USER_LOADING="USER_LOADING";
//export const GET_AUTH_USER="GET_AUTH_USER";
export const DELETE_MEDICALFILE="DELETE_MEDICALFILE";
export const EDIT_MEDICALFILES="EDIT_MEDICALFILES";
export const GET_FILE="GET_FILE";

//Appointement

export const POST_APPOINTMENTS="POST_APPOINTMENTS";

export const GET_APPOINTMENTS="GET_APPOINTMENTS";
export const DELETE_APPOINTMENT="DELETE_APPOINTMENT";

